/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type Copyright = {
  _id: string;
  _type: "copyright";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Socials = {
  _id: string;
  _type: "socials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  socials?: Array<{
    _key: string;
  } & Social>;
};

export type Social = {
  _type: "social";
  title?: string;
  link?: string;
  icon?: Icon;
};

export type Locations = {
  _id: string;
  _type: "locations";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  city?: string;
  address?: string;
  postalCode?: string;
  email?: string;
  phone?: string;
  menu?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "dishesMenu";
  };
  monday?: Duration;
  tuesday?: Duration;
  wednesday?: Duration;
  thursday?: Duration;
  friday?: Duration;
  saturday?: Duration;
  sunday?: Duration;
};

export type Duration = {
  _type: "duration";
  morningStart?: "00:00" | "00:30" | "01:00" | "01:30" | "02:00" | "02:30" | "03:00" | "03:30" | "04:00" | "04:30" | "05:00" | "05:30" | "06:00" | "06:30" | "07:00" | "07:30" | "08:00" | "08:30" | "09:00" | "09:30" | "10:00" | "10:30" | "11:00" | "11:30" | "12:00" | "12:30" | "13:00" | "13:30" | "14:00" | "14:30" | "15:00" | "15:30" | "16:00" | "16:30" | "17:00" | "17:30" | "18:00" | "18:30" | "19:00" | "19:30" | "20:00" | "20:30" | "21:00" | "21:30" | "22:00" | "22:30" | "23:00" | "23:30";
  morningEnd?: "00:00" | "00:30" | "01:00" | "01:30" | "02:00" | "02:30" | "03:00" | "03:30" | "04:00" | "04:30" | "05:00" | "05:30" | "06:00" | "06:30" | "07:00" | "07:30" | "08:00" | "08:30" | "09:00" | "09:30" | "10:00" | "10:30" | "11:00" | "11:30" | "12:00" | "12:30" | "13:00" | "13:30" | "14:00" | "14:30" | "15:00" | "15:30" | "16:00" | "16:30" | "17:00" | "17:30" | "18:00" | "18:30" | "19:00" | "19:30" | "20:00" | "20:30" | "21:00" | "21:30" | "22:00" | "22:30" | "23:00" | "23:30";
  eveningStart?: "00:00" | "00:30" | "01:00" | "01:30" | "02:00" | "02:30" | "03:00" | "03:30" | "04:00" | "04:30" | "05:00" | "05:30" | "06:00" | "06:30" | "07:00" | "07:30" | "08:00" | "08:30" | "09:00" | "09:30" | "10:00" | "10:30" | "11:00" | "11:30" | "12:00" | "12:30" | "13:00" | "13:30" | "14:00" | "14:30" | "15:00" | "15:30" | "16:00" | "16:30" | "17:00" | "17:30" | "18:00" | "18:30" | "19:00" | "19:30" | "20:00" | "20:30" | "21:00" | "21:30" | "22:00" | "22:30" | "23:00" | "23:30";
  eveningEnd?: "00:00" | "00:30" | "01:00" | "01:30" | "02:00" | "02:30" | "03:00" | "03:30" | "04:00" | "04:30" | "05:00" | "05:30" | "06:00" | "06:30" | "07:00" | "07:30" | "08:00" | "08:30" | "09:00" | "09:30" | "10:00" | "10:30" | "11:00" | "11:30" | "12:00" | "12:30" | "13:00" | "13:30" | "14:00" | "14:30" | "15:00" | "15:30" | "16:00" | "16:30" | "17:00" | "17:30" | "18:00" | "18:30" | "19:00" | "19:30" | "20:00" | "20:30" | "21:00" | "21:30" | "22:00" | "22:30" | "23:00" | "23:30";
  closed?: boolean;
};

export type TimeValue = "00:00" | "00:30" | "01:00" | "01:30" | "02:00" | "02:30" | "03:00" | "03:30" | "04:00" | "04:30" | "05:00" | "05:30" | "06:00" | "06:30" | "07:00" | "07:30" | "08:00" | "08:30" | "09:00" | "09:30" | "10:00" | "10:30" | "11:00" | "11:30" | "12:00" | "12:30" | "13:00" | "13:30" | "14:00" | "14:30" | "15:00" | "15:30" | "16:00" | "16:30" | "17:00" | "17:30" | "18:00" | "18:30" | "19:00" | "19:30" | "20:00" | "20:30" | "21:00" | "21:30" | "22:00" | "22:30" | "23:00" | "23:30";

export type Dish = {
  _type: "dish";
  title?: string;
  description?: string;
  price?: number;
};

export type DishesCategory = {
  _type: "dishesCategory";
  title?: string;
  icon?: Icon;
  dishes?: Array<{
    _key: string;
  } & Dish>;
};

export type DishesMenu = {
  _id: string;
  _type: "dishesMenu";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  introText?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  categories?: Array<{
    _key: string;
  } & DishesCategory>;
};

export type Map = {
  _type: "map";
  heading?: string;
  mapCenter?: Geopoint;
  locations?: Array<{
    _key: string;
  } & Geopoint>;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Link = {
  _type: "link";
  internalLink?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "page";
  };
  externalUrl?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  navId?: Slug;
  items?: Array<{
    _key: string;
  } & NavigationItem>;
};

export type Separator = {
  _type: "separator";
  separatorColor?: Color;
};

export type Slideshow = {
  _type: "slideshow";
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    heading?: string;
    subtitle?: string;
    cta?: NavigationItem;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Slider = {
  _type: "slider";
  heading?: string;
  subtitle?: string;
  backgroundImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Video = {
  _type: "video";
  videoLabel?: string;
  cssClasses?: string;
  file?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    _type: "file";
  };
};

export type Form = {
  _type: "form";
  label?: string;
  heading?: string;
  form?: "newsletter" | "register" | "contact";
};

export type Gallery = {
  _type: "gallery";
  heading?: string;
  subtitle?: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type TextWithIllustration = {
  _type: "textWithIllustration";
  heading?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  imagePosition?: "left" | "right";
  gridSize?: "grid-cols-2" | "grid-cols-3";
};

export type Banner = {
  _type: "banner";
  heading?: string;
  headingCSSClasses?: string;
  subtitle?: string;
  text?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type Promotion = {
  _type: "promotion";
  title?: string;
  link?: string;
  direction?: "left" | "right";
  speed?: number;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  subtitle?: string;
  slug?: Slug;
  metaTitle?: string;
  metaDescription?: string;
  introImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  fullWidth?: boolean;
  pageBuilder?: Array<{
    _key: string;
  } & Banner | {
    _key: string;
  } & TextWithIllustration | {
    _key: string;
  } & Gallery | {
    _key: string;
  } & Slider | {
    _key: string;
  } & Slideshow | {
    _key: string;
  } & Form | {
    _key: string;
  } & Video | {
    _key: string;
  } & Promotion | {
    _key: string;
  } & Separator | {
    _key: string;
  } & Map | {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "dishesMenu";
  }>;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type NavigationItem = {
  _type: "navigationItem";
  text?: string;
  navigationItemUrl?: Link;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type Icon = {
  _type: "icon";
  name?: string;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | Copyright | Socials | Social | Locations | Duration | TimeValue | Dish | DishesCategory | DishesMenu | Map | Geopoint | Link | Navigation | Separator | Slideshow | Slider | Video | Form | Gallery | TextWithIllustration | Banner | Promotion | BlockContent | Page | SanityFileAsset | NavigationItem | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Slug | Color | RgbaColor | HsvaColor | HslaColor | Icon;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: HEADERMENU_QUERY
// Query: *[navId.current match "main-menu*"]{  'navId': navId.current,  'items':  items[] {    'link': *[      _type == "page" &&      _id == ^.navigationItemUrl.internalLink._ref    ][0]{      'slug': slug.current    },    'externalUrl': navigationItemUrl.externalUrl,    text  }}
export type HEADERMENU_QUERYResult = Array<{
  navId: string | null;
  items: Array<{
    link: {
      slug: string | null;
    } | null;
    externalUrl: string | null;
    text: string | null;
  }> | null;
}>;
// Variable: SOCIALS_QUERY
// Query: *[_type == "socials"][0].socials
export type SOCIALS_QUERYResult = Array<{
  _key: string;
} & Social> | null;
// Variable: LOCATIONS_QUERY
// Query: *[_type == "locations"]{  title,  city,  address,  postalCode,  phone,  email,  monday,  tuesday,  wednesday,  thursday,  friday,  saturday,  sunday}
export type LOCATIONS_QUERYResult = Array<{
  title: string | null;
  city: string | null;
  address: string | null;
  postalCode: string | null;
  phone: string | null;
  email: string | null;
  monday: Duration | null;
  tuesday: Duration | null;
  wednesday: Duration | null;
  thursday: Duration | null;
  friday: Duration | null;
  saturday: Duration | null;
  sunday: Duration | null;
}>;
// Variable: COPYRIGHT_QUERY
// Query: *[_type == "copyright"][0].content
export type COPYRIGHT_QUERYResult = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
  _key: string;
}> | null;
// Variable: HOMEPAGE_QUERY
// Query: *[slug.current match "home*"][0]{  title,  subtitle,  slug,  metaTitle,  metaDescription,  fullWidth,  pageBuilder[]{    _type == "video" => {      _type,      videoLabel,      cssClasses,      file    },    _type == "banner" => {      _type,      heading,      text,      headingCSSClasses,      subtitle    },    _type == "separator" => {      _type,      separatorColor    },    _type == "slider" => {      _type,      heading,      subtitle,      backgroundImage,      images    },    _type == "slideshow" => {      _type,      'images':  images[] {        asset,        hotspot,        crop,        alt,        heading,        subtitle,        'link': *[_type == "page" && _id == ^.cta.navigationItemUrl.internalLink._ref][0]{          'slug': slug.current        },        'externalUrl': cta.navigationItemUrl.externalUrl,        'ctaText': cta.text      }    },    _type == "textWithIllustration" => {      _type,      heading,      text,      image,      imagePosition,      gridSize    },    _type == "gallery" => {      _type,      heading,      subtitle,      images    },    _type == "form" => {      _type,      heading,      label,      form    },    _type == "promotion" => {      _type,      title,      link,      direction,      speed    },    _type == "map" => {      _type,      heading,      mapCenter,      locations    },    _type == "dishesMenu" => {      _type,      _ref,      "menu": *[ _type == "dishesMenu" && menu._ref == ^._id ][0] {        title,        introText,        categories      }    }  },}
export type HOMEPAGE_QUERYResult = {
  title: string | null;
  subtitle: string | null;
  slug: Slug | null;
  metaTitle: string | null;
  metaDescription: string | null;
  fullWidth: boolean | null;
  pageBuilder: Array<{
    _type: "banner";
    heading: string | null;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
    headingCSSClasses: string | null;
    subtitle: string | null;
  } | {
    _type: "form";
    heading: string | null;
    label: string | null;
    form: "contact" | "newsletter" | "register" | null;
  } | {
    _type: "gallery";
    heading: string | null;
    subtitle: string | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
  } | {
    _type: "map";
    heading: string | null;
    mapCenter: Geopoint | null;
    locations: Array<{
      _key: string;
    } & Geopoint> | null;
  } | {
    _type: "promotion";
    title: string | null;
    link: string | null;
    direction: "left" | "right" | null;
    speed: number | null;
  } | {
    _type: "separator";
    separatorColor: Color | null;
  } | {
    _type: "slider";
    heading: string | null;
    subtitle: string | null;
    backgroundImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
  } | {
    _type: "slideshow";
    images: Array<{
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      heading: string | null;
      subtitle: string | null;
      link: {
        slug: string | null;
      } | null;
      externalUrl: string | null;
      ctaText: string | null;
    }> | null;
  } | {
    _type: "textWithIllustration";
    heading: string | null;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    imagePosition: "left" | "right" | null;
    gridSize: "grid-cols-2" | "grid-cols-3" | null;
  } | {
    _type: "video";
    videoLabel: string | null;
    cssClasses: string | null;
    file: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      _type: "file";
    } | null;
  } | {}> | null;
} | null;
// Variable: PAGE_QUERY
// Query: *[slug.current == $slug][0]{  title,  subtitle,  slug,  metaTitle,  metaDescription,  introImage,  fullWidth,  pageBuilder[]{    _type == "video" => {      _type,      videoLabel,      cssClasses,      file    },    _type == "banner" => {      _type,      heading,      text,      headingCSSClasses,      subtitle    },    _type == "separator" => {      _type,      separatorColor    },    _type == "slider" => {      _type,      title,      subtitle,      backgroundImage,      images    },    _type == "slideshow" => {      _type,      'images':  images[] {        asset,        hotspot,        crop,        alt,        heading,        subtitle,        'link': *[_type == "page" && _id == ^.cta.navigationItemUrl.internalLink._ref][0]{          'slug': slug.current        },        'externalUrl': cta.navigationItemUrl.externalUrl,        'ctaText': cta.text      }    },    _type == "textWithIllustration" => {      _type,      heading,      text,      image,      imagePosition,      gridSize    },    _type == "gallery" => {      _type,      heading,      subtitle,      images    },    _type == "form" => {      _type,      heading,      label,      form    },    _type == "promotion" => {      _type,      title,      link,      direction,      speed    },    _type == "map" => {      _type,      heading,      mapCenter,      locations    },    _type == "dishesMenu" => {      _type,      _ref,      "menu": *[_type == "dishesMenu" && ^._ref == _id][0] {        _id,        title,        introText,        categories      }    }  },}
export type PAGE_QUERYResult = {
  title: null;
  subtitle: null;
  slug: null;
  metaTitle: null;
  metaDescription: null;
  introImage: null;
  fullWidth: null;
  pageBuilder: null;
} | {
  title: string | null;
  subtitle: null;
  slug: null;
  metaTitle: null;
  metaDescription: null;
  introImage: null;
  fullWidth: null;
  pageBuilder: null;
} | {
  title: string | null;
  subtitle: string | null;
  slug: Slug | null;
  metaTitle: string | null;
  metaDescription: string | null;
  introImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  fullWidth: boolean | null;
  pageBuilder: Array<{
    _type: "banner";
    heading: string | null;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
    headingCSSClasses: string | null;
    subtitle: string | null;
  } | {
    _type: "form";
    heading: string | null;
    label: string | null;
    form: "contact" | "newsletter" | "register" | null;
  } | {
    _type: "gallery";
    heading: string | null;
    subtitle: string | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
  } | {
    _type: "map";
    heading: string | null;
    mapCenter: Geopoint | null;
    locations: Array<{
      _key: string;
    } & Geopoint> | null;
  } | {
    _type: "promotion";
    title: string | null;
    link: string | null;
    direction: "left" | "right" | null;
    speed: number | null;
  } | {
    _type: "separator";
    separatorColor: Color | null;
  } | {
    _type: "slider";
    title: null;
    subtitle: string | null;
    backgroundImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    images: Array<{
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
  } | {
    _type: "slideshow";
    images: Array<{
      asset: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      } | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: string | null;
      heading: string | null;
      subtitle: string | null;
      link: {
        slug: string | null;
      } | null;
      externalUrl: string | null;
      ctaText: string | null;
    }> | null;
  } | {
    _type: "textWithIllustration";
    heading: string | null;
    text: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }> | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    imagePosition: "left" | "right" | null;
    gridSize: "grid-cols-2" | "grid-cols-3" | null;
  } | {
    _type: "video";
    videoLabel: string | null;
    cssClasses: string | null;
    file: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      _type: "file";
    } | null;
  } | {}> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[navId.current match \"main-menu*\"]{\n  'navId': navId.current,\n  'items':  items[] {\n    'link': *[\n      _type == \"page\" &&\n      _id == ^.navigationItemUrl.internalLink._ref\n    ][0]{\n      'slug': slug.current\n    },\n    'externalUrl': navigationItemUrl.externalUrl,\n    text\n  }\n}": HEADERMENU_QUERYResult;
    "*[_type == \"socials\"][0].socials": SOCIALS_QUERYResult;
    "*[_type == \"locations\"]{\n  title,\n  city,\n  address,\n  postalCode,\n  phone,\n  email,\n  monday,\n  tuesday,\n  wednesday,\n  thursday,\n  friday,\n  saturday,\n  sunday\n}": LOCATIONS_QUERYResult;
    "*[_type == \"copyright\"][0].content": COPYRIGHT_QUERYResult;
    "*[slug.current match \"home*\"][0]{\n  title,\n  subtitle,\n  slug,\n  metaTitle,\n  metaDescription,\n  fullWidth,\n  pageBuilder[]{\n    _type == \"video\" => {\n      _type,\n      videoLabel,\n      cssClasses,\n      file\n    },\n    _type == \"banner\" => {\n      _type,\n      heading,\n      text,\n      headingCSSClasses,\n      subtitle\n    },\n    _type == \"separator\" => {\n      _type,\n      separatorColor\n    },\n    _type == \"slider\" => {\n      _type,\n      heading,\n      subtitle,\n      backgroundImage,\n      images\n    },\n    _type == \"slideshow\" => {\n      _type,\n      'images':  images[] {\n        asset,\n        hotspot,\n        crop,\n        alt,\n        heading,\n        subtitle,\n        'link': *[_type == \"page\" && _id == ^.cta.navigationItemUrl.internalLink._ref][0]{\n          'slug': slug.current\n        },\n        'externalUrl': cta.navigationItemUrl.externalUrl,\n        'ctaText': cta.text\n      }\n    },\n    _type == \"textWithIllustration\" => {\n      _type,\n      heading,\n      text,\n      image,\n      imagePosition,\n      gridSize\n    },\n    _type == \"gallery\" => {\n      _type,\n      heading,\n      subtitle,\n      images\n    },\n    _type == \"form\" => {\n      _type,\n      heading,\n      label,\n      form\n    },\n    _type == \"promotion\" => {\n      _type,\n      title,\n      link,\n      direction,\n      speed\n    },\n    _type == \"map\" => {\n      _type,\n      heading,\n      mapCenter,\n      locations\n    },\n    _type == \"dishesMenu\" => {\n      _type,\n      _ref,\n      \"menu\": *[ _type == \"dishesMenu\" && menu._ref == ^._id ][0] {\n        title,\n        introText,\n        categories\n      }\n    }\n  },\n}": HOMEPAGE_QUERYResult;
    "*[slug.current == $slug][0]{\n  title,\n  subtitle,\n  slug,\n  metaTitle,\n  metaDescription,\n  introImage,\n  fullWidth,\n  pageBuilder[]{\n    _type == \"video\" => {\n      _type,\n      videoLabel,\n      cssClasses,\n      file\n    },\n    _type == \"banner\" => {\n      _type,\n      heading,\n      text,\n      headingCSSClasses,\n      subtitle\n    },\n    _type == \"separator\" => {\n      _type,\n      separatorColor\n    },\n    _type == \"slider\" => {\n      _type,\n      title,\n      subtitle,\n      backgroundImage,\n      images\n    },\n    _type == \"slideshow\" => {\n      _type,\n      'images':  images[] {\n        asset,\n        hotspot,\n        crop,\n        alt,\n        heading,\n        subtitle,\n        'link': *[_type == \"page\" && _id == ^.cta.navigationItemUrl.internalLink._ref][0]{\n          'slug': slug.current\n        },\n        'externalUrl': cta.navigationItemUrl.externalUrl,\n        'ctaText': cta.text\n      }\n    },\n    _type == \"textWithIllustration\" => {\n      _type,\n      heading,\n      text,\n      image,\n      imagePosition,\n      gridSize\n    },\n    _type == \"gallery\" => {\n      _type,\n      heading,\n      subtitle,\n      images\n    },\n    _type == \"form\" => {\n      _type,\n      heading,\n      label,\n      form\n    },\n    _type == \"promotion\" => {\n      _type,\n      title,\n      link,\n      direction,\n      speed\n    },\n    _type == \"map\" => {\n      _type,\n      heading,\n      mapCenter,\n      locations\n    },\n    _type == \"dishesMenu\" => {\n      _type,\n      _ref,\n      \"menu\": *[_type == \"dishesMenu\" && ^._ref == _id][0] {\n        _id,\n        title,\n        introText,\n        categories\n      }\n    }\n  },\n}": PAGE_QUERYResult;
  }
}
